# Generated by Django 3.2.7 on 2021-09-29 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainuser',
            old_name='is_user',
            new_name='is_simple_user',
        ),
    ]
