# Generated by Django 3.2.7 on 2021-09-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210216_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
