# Generated by Django 3.2.7 on 2021-09-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers'),
        ),
    ]
